// SPDX-License-Identifier: MIT
package main

import (
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"runtime"
	"strings"
	"testing"
)

// The npm distribution is five packages generated by `make npm-dist` from the templates in
// npm/: a launcher that resolves the host's platform package, and one package per platform
// carrying the static binary. These tests pin the properties of that layout that can drift
// silently — an install script appearing, a platform going unpinned, the package name being
// hardcoded in a second place — because every one of them fails at a user's `npm i`, long
// after the release that introduced it.

func repoRoot() string { return filepath.Join("..", "..") }

// makeVar reads a simple `NAME := value` assignment out of the Makefile. The Makefile is the
// single source of truth for both the package name and the platform list, so the tests read
// it rather than restating either.
func makeVar(t *testing.T, name string) string {
	t.Helper()
	b, err := os.ReadFile(filepath.Join(repoRoot(), "Makefile"))
	if err != nil {
		t.Fatal(err)
	}
	re := regexp.MustCompile(`(?m)^` + regexp.QuoteMeta(name) + `\s*:?\??=\s*(.+?)\s*$`)
	m := re.FindSubmatch(b)
	if m == nil {
		t.Fatalf("Makefile has no %s assignment", name)
	}
	return string(m[1])
}

// npmPlatformSuffixes maps the Makefile's Go platform list to npm's spelling. amd64 is x64 in
// npm's cpu field, and that single rename is the whole mapping — getting it wrong produces a
// launcher that cannot resolve the package it just installed.
func npmPlatformSuffixes(t *testing.T) []string {
	t.Helper()
	var out []string
	for _, target := range strings.Fields(makeVar(t, "DIST_TARGETS")) {
		os_, arch, ok := strings.Cut(target, "/")
		if !ok {
			t.Fatalf("DIST_TARGETS entry %q is not os/arch", target)
		}
		if arch == "amd64" {
			arch = "x64"
		}
		out = append(out, os_+"-"+arch)
	}
	return out
}

func readTemplate(t *testing.T, name string) map[string]any {
	t.Helper()
	b, err := os.ReadFile(filepath.Join(repoRoot(), "npm", name))
	if err != nil {
		t.Fatal(err)
	}
	// The placeholders sit inside JSON strings, so a template is still valid JSON.
	var doc map[string]any
	if err := json.Unmarshal(b, &doc); err != nil {
		t.Fatalf("%s is not valid JSON: %v", name, err)
	}
	return doc
}

// TestNpmPackagesHaveNoInstallScripts is the load-bearing one. The common way to put a
// compiled binary on npm is a postinstall script that downloads it — which is the shape this
// scanner reports in other people's repositories (fetch-then-run), so shipping it here would
// make the tool contradict its own README. The binary is IN the tarball instead, and npm picks
// the right package from the os/cpu fields. An install script appearing in either template is
// this property being lost.
func TestNpmPackagesHaveNoInstallScripts(t *testing.T) {
	for _, name := range []string{"package.json.tmpl", "platform.package.json.tmpl"} {
		if scripts, ok := readTemplate(t, name)["scripts"]; ok {
			t.Errorf("%s declares scripts (%v); the npm packages must have none — "+
				"a download-then-run postinstall is the shape this tool reports on others", name, scripts)
		}
	}
}

// TestNpmLauncherPinsEveryDistTarget: the launcher reaches its binary through
// optionalDependencies, so a platform that is built but not pinned ships a launcher that exits
// 2 on that host, and a pinned platform that is not built publishes a dangling dependency.
// Both are release-time breakage discovered by users, so the two lists must agree exactly.
func TestNpmLauncherPinsEveryDistTarget(t *testing.T) {
	launcher := readTemplate(t, "package.json.tmpl")
	deps, ok := launcher["optionalDependencies"].(map[string]any)
	if !ok {
		t.Fatal("launcher template has no optionalDependencies")
	}
	got := map[string]bool{}
	for dep, ver := range deps {
		suffix, ok := strings.CutPrefix(dep, "__NAME__-")
		if !ok {
			t.Errorf("optionalDependency %q must be derived from __NAME__ so the package name has one source", dep)
			continue
		}
		if ver != "__VERSION__" {
			t.Errorf("optionalDependency %q is pinned to %v, want the exact __VERSION__ placeholder", dep, ver)
		}
		got[suffix] = true
	}
	want := npmPlatformSuffixes(t)
	if len(got) != len(want) {
		t.Errorf("launcher pins %d platforms, DIST_TARGETS builds %d", len(got), len(want))
	}
	for _, suffix := range want {
		if !got[suffix] {
			t.Errorf("DIST_TARGETS builds %s but the launcher does not pin __NAME__-%s", suffix, suffix)
		}
	}
}

// TestNpmLauncherAndPlatformRolesStayApart: the launcher must install everywhere (it is what
// `npm i` resolves first), so it carries no os/cpu restriction and owns the bin entry; the
// platform packages are the opposite. Swapping either half breaks installation on every host
// that is not the maintainer's.
func TestNpmLauncherAndPlatformRolesStayApart(t *testing.T) {
	launcher := readTemplate(t, "package.json.tmpl")
	if _, ok := launcher["os"]; ok {
		t.Error("launcher template declares os; it must be installable on every platform")
	}
	if _, ok := launcher["cpu"]; ok {
		t.Error("launcher template declares cpu; it must be installable on every platform")
	}
	bin, ok := launcher["bin"].(map[string]any)
	if !ok || bin["aguard"] != "bin/aguard.js" {
		t.Errorf("launcher must expose bin.aguard = bin/aguard.js, got %v", launcher["bin"])
	}
	// `files` is what decides whether the bin target reaches the tarball, so declaring the bin
	// entry is only half of it. Omitting the file publishes a package whose `aguard` command
	// points at something that is not there — broken for every user, and both fields would
	// still look individually well-formed.
	shipped := map[string]bool{}
	files, _ := launcher["files"].([]any)
	for _, f := range files {
		if s, isStr := f.(string); isStr {
			shipped[s] = true
		}
	}
	for cmdName, target := range bin {
		if s, isStr := target.(string); !isStr || !shipped[s] {
			t.Errorf("bin.%s points at %v, which files does not ship (%v)", cmdName, target, launcher["files"])
		}
	}

	platform := readTemplate(t, "platform.package.json.tmpl")
	for _, field := range []string{"os", "cpu"} {
		if _, ok := platform[field]; !ok {
			t.Errorf("platform template must declare %s so npm installs only the matching one", field)
		}
	}
	if _, ok := platform["bin"]; ok {
		t.Error("platform template declares bin; the launcher resolves the binary, the platform package only carries it")
	}
}

// TestNpmPackageNameHasOneSource: renaming the published package must be one Makefile line.
// The launcher derives its platform packages from its own package.json name at run time, so a
// scope hardcoded in the shim would survive a rename and resolve to a package nobody publishes.
func TestNpmPackageNameHasOneSource(t *testing.T) {
	name := makeVar(t, "NPM_NAME")
	if name == "" {
		t.Fatal("NPM_NAME is empty")
	}
	b, err := os.ReadFile(filepath.Join(repoRoot(), "npm", "bin", "aguard.js"))
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(b), name) {
		t.Errorf("npm/bin/aguard.js hardcodes the package name %q; it must read it from ../package.json", name)
	}
}

// TestEphemeralExeWarningNamesOnlyDisposablePaths: the npm route makes it easy to run the tool
// from a cache npm will reclaim, and `hook install` bakes an absolute path into settings.json.
// So the warning has to fire for those paths — and must NOT fire for the ordinary install
// locations, because a warning that shows up on a normal `npm i -g` is one operators learn to
// scroll past, and this is the one they need to read.
func TestEphemeralExeWarningNamesOnlyDisposablePaths(t *testing.T) {
	disposable := []string{
		"/Users/x/.npm/_npx/2f3a9c/node_modules/@scope/pkg-darwin-arm64/aguard",
		"/home/x/.npm/_cacache/tmp/abc/aguard",
	}
	stable := []string{
		"/usr/local/bin/aguard",
		"/Users/x/.local/bin/aguard",
		// A global npm install: inside node_modules, but a path npm keeps until uninstall.
		"/usr/local/lib/node_modules/@scope/pkg-darwin-arm64/aguard",
		// Paths that merely mention the words must not trip a segment match.
		"/Users/x/projects/_npx-notes/aguard",
		"/opt/my_cacache_backup/aguard",
	}
	for _, p := range disposable {
		if ephemeralExeWarning(p) == "" {
			t.Errorf("no warning for %s; a gate installed from there becomes GATE-001 when the cache is reclaimed", p)
		}
	}
	for _, p := range stable {
		if w := ephemeralExeWarning(p); w != "" {
			t.Errorf("warned about the stable path %s:\n%s", p, w)
		}
	}
}

// hostPlatformSuffix is the suffix the launcher will look for on the machine running the test,
// using npm's arch spelling. Only the shipped platforms are covered, which is also the only
// place the tests run.
func hostPlatformSuffix() (string, bool) {
	arch := runtime.GOARCH
	if arch == "amd64" {
		arch = "x64"
	}
	if runtime.GOOS != "darwin" && runtime.GOOS != "linux" {
		return "", false
	}
	if arch != "x64" && arch != "arm64" {
		return "", false
	}
	return runtime.GOOS + "-" + arch, true
}

// fakeLauncherTree builds a launcher package next to one platform package whose "binary" is a
// script the caller controls, so the launcher's own exit-code handling can be exercised without
// a cross-compiled dist/ or a real scan.
func fakeLauncherTree(t *testing.T, script string) string {
	t.Helper()
	suffix, ok := hostPlatformSuffix()
	if !ok {
		t.Skipf("no platform package for %s/%s", runtime.GOOS, runtime.GOARCH)
	}
	shim, err := os.ReadFile(filepath.Join(repoRoot(), "npm", "bin", "aguard.js"))
	if err != nil {
		t.Fatal(err)
	}
	root := t.TempDir()
	const name = "@example/fake"
	mustWrite := func(path, content string, mode os.FileMode) {
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(content), mode); err != nil {
			t.Fatal(err)
		}
	}
	// optionalDependencies is not decoration here: the launcher derives the platforms it
	// supports from this list, so a fixture without it would be refused before it ever looked
	// for the binary.
	mustWrite(filepath.Join(root, "package.json"), `{"name":"`+name+`","version":"0.0.0-test",`+
		`"optionalDependencies":{"`+name+`-`+suffix+`":"0.0.0-test"}}`, 0o644)
	mustWrite(filepath.Join(root, "bin", "aguard.js"), string(shim), 0o755)
	mustWrite(filepath.Join(root, "node_modules", name+"-"+suffix, "aguard"), script, 0o755)
	return root
}

// TestNpmLauncherReproducesTheBinarysExit: the launcher is meant to be transparent — whatever
// the binary would have told the shell, it tells the shell. Three cases matter:
//
//   - an ordinary exit code passes through unchanged, including 3, which `clean` uses for
//     "acted partially" and which a launcher that collapsed non-zero codes would destroy;
//   - a signal must NOT become 0. `process.exitCode = null` (what assigning result.status
//     directly does) exits 0, which in this tool reads as "below threshold" — a killed scan
//     rendered as a clean one. 128+signal is what a shell reports for the binary itself;
//   - SIGPIPE is the one signal that is routine rather than alarming: `aguard scan | head`
//     closes the pipe deliberately. It still must not exit 0, but it must stay quiet, or every
//     piped invocation grows a warning nobody needs.
func TestNpmLauncherReproducesTheBinarysExit(t *testing.T) {
	node, err := exec.LookPath("node")
	if err != nil {
		t.Skip("node not installed; the launcher is only reachable through it")
	}
	cases := []struct {
		name     string
		script   string
		wantCode int
		wantErr  string // substring required on stderr; empty means stderr must stay silent
	}{
		{
			name:     "clean partial exit passes through",
			script:   "#!/bin/sh\nexit 3\n",
			wantCode: 3,
		},
		{
			// Ctrl-C. The single most common way a long scan ends, and the binary alone says
			// nothing about it, so neither may the launcher.
			name:     "interrupt is non-zero but silent",
			script:   "#!/bin/sh\nkill -INT $$\n",
			wantCode: 128 + 2,
		},
		{
			// `aguard scan | head` — the downstream closed the pipe on purpose.
			name:     "sigpipe is non-zero but silent",
			script:   "#!/bin/sh\nkill -PIPE $$\n",
			wantCode: 128 + 13,
		},
		{
			// `kill <pid>`, and what a shutting-down container sends. Also ordinary.
			name:     "terminate is non-zero but silent",
			script:   "#!/bin/sh\nkill -TERM $$\n",
			wantCode: 128 + 15,
		},
		{
			// Not a request to stop: the binary failed. This is the one worth a line.
			name:     "a crash signal is reported",
			script:   "#!/bin/sh\nkill -ABRT $$\n",
			wantCode: 128 + 6,
			wantErr:  "SIGABRT",
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			root := fakeLauncherTree(t, tc.script)
			cmd := exec.Command(node, filepath.Join(root, "bin", "aguard.js"), "scan")
			var stderr strings.Builder
			cmd.Stderr = &stderr
			_ = cmd.Run()
			if got := cmd.ProcessState.ExitCode(); got != tc.wantCode {
				t.Errorf("exit code = %d, want %d (stderr: %s)", got, tc.wantCode, stderr.String())
			}
			switch {
			case tc.wantErr == "" && strings.TrimSpace(stderr.String()) != "":
				t.Errorf("expected no diagnostic, got: %s", stderr.String())
			case tc.wantErr != "" && !strings.Contains(stderr.String(), tc.wantErr):
				t.Errorf("stderr must mention %q, got: %s", tc.wantErr, stderr.String())
			}
		})
	}
}

// TestNpmLauncherExitsTwoWhenThePlatformBinaryIsMissing: exit codes are this tool's contract
// (0 below threshold, 1 a finding at or above --fail-on, 2 runtime error), so the launcher may
// never report 0 for a run that produced no verdict. A missing platform package is the
// realistic way to get there — installed with --no-optional, or restored from a lockfile built
// on another OS — and the widespread `process.exitCode = result.status` ending returns 0 for
// exactly this class of non-answer. 2 means "the scan did not happen", which is the truth.
func TestNpmLauncherExitsTwoWhenThePlatformBinaryIsMissing(t *testing.T) {
	node, err := exec.LookPath("node")
	if err != nil {
		t.Skip("node not installed; the launcher is only reachable through it")
	}
	// The platform package is DECLARED but not installed — the launcher's platform check
	// passes and the resolve is what fails. That is what npm leaves behind after
	// --no-optional, a lockfile from another OS, or an engine mismatch skipping it.
	root := fakeLauncherTree(t, "#!/bin/sh\nexit 0\n")
	if err := os.RemoveAll(filepath.Join(root, "node_modules")); err != nil {
		t.Fatal(err)
	}

	cmd := exec.Command(node, filepath.Join(root, "bin", "aguard.js"), "version")
	out, err := cmd.CombinedOutput()
	code := cmd.ProcessState.ExitCode()
	if code != 2 {
		t.Fatalf("exit code = %d (err %v), want 2 — a launcher that cannot run the scanner must not report success.\n%s", code, err, out)
	}
	if !strings.Contains(string(out), "@example/fake-") {
		t.Errorf("the error must name the platform package that is missing, got:\n%s", out)
	}
}

// TestNpmLauncherKeepsNoPlatformListOfItsOwn: the launcher decides which platforms it supports
// by reading its own optionalDependencies, so DIST_TARGETS -> optionalDependencies (checked
// above) -> launcher is one chain with no second copy to drift. A hardcoded os or cpu name
// reintroduces that copy, and the failure it produces is invisible to the other tests: a
// platform that is built AND pinned would still be refused with "no prebuilt binary" on a
// machine where npm had installed its binary.
func TestNpmLauncherKeepsNoPlatformListOfItsOwn(t *testing.T) {
	b, err := os.ReadFile(filepath.Join(repoRoot(), "npm", "bin", "aguard.js"))
	if err != nil {
		t.Fatal(err)
	}
	// Only the literals that would form such a list: the comment explaining the design names
	// signals and rule IDs, not platforms.
	for _, literal := range []string{`"darwin"`, `"linux"`, `"x64"`, `"arm64"`} {
		if strings.Contains(string(b), literal) {
			t.Errorf("npm/bin/aguard.js contains the platform literal %s; it must derive the "+
				"supported set from its own optionalDependencies instead", literal)
		}
	}
}
