// SPDX-License-Identifier: MIT

package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
)

// goldenFiles are the outputs pinned byte for byte (incomplete.jsonl is checked structurally).
var goldenFiles = []string{"judge.jsonl", "verdicts.jsonl", "ledger.jsonl", "per-kind-rule.txt"}

// compareGolden compares the fold's outputs with golden_values_test.go, or rewrites that file
// when JUDGEFOLD_WRITE_GOLDEN=1. The goldens live in Go source rather than a testdata/ directory,
// which this repository does not have; one string per line keeps a regenerated diff readable.
func compareGolden(t *testing.T, out string) {
	t.Helper()
	got := map[string][]string{}
	for _, name := range goldenFiles {
		b, err := os.ReadFile(filepath.Join(out, name))
		if err != nil {
			t.Errorf("%s: %v", name, err)
			return
		}
		got[name] = strings.SplitAfter(string(b), "\n")
	}
	if os.Getenv("JUDGEFOLD_WRITE_GOLDEN") == "1" {
		writeGolden(t, got)
		return
	}
	for _, name := range goldenFiles {
		want, have := golden[name], got[name]
		if strings.Join(want, "") == strings.Join(have, "") {
			continue
		}
		for i := 0; i < len(want) || i < len(have); i++ {
			var w, h string
			if i < len(want) {
				w = want[i]
			}
			if i < len(have) {
				h = have[i]
			}
			if w != h {
				t.Errorf("%s differs from its golden at line %d:\n got %q\nwant %q\n(JUDGEFOLD_WRITE_GOLDEN=1 regenerates; review the diff)", name, i+1, h, w)
				break
			}
		}
	}
}

func writeGolden(t *testing.T, got map[string][]string) {
	t.Helper()
	var b strings.Builder
	b.WriteString("// SPDX-License-Identifier: MIT\n\n// Code generated by TestJudgefold_Golden with JUDGEFOLD_WRITE_GOLDEN=1. DO NOT EDIT.\n// Review the diff of a regeneration line by line: each line is an output of the fold.\n\npackage main\n\nvar golden = map[string][]string{\n")
	names := make([]string, 0, len(got))
	for n := range got {
		names = append(names, n)
	}
	sort.Strings(names)
	for _, n := range names {
		fmt.Fprintf(&b, "\t%q: {\n", n)
		for _, l := range got[n] {
			if l != "" {
				fmt.Fprintf(&b, "\t\t%q,\n", l)
			}
		}
		b.WriteString("\t},\n")
	}
	b.WriteString("}\n")
	if err := os.WriteFile("golden_values_test.go", []byte(b.String()), 0o644); err != nil {
		t.Fatal(err)
	}
	t.Log("rewrote golden_values_test.go")
}
