// SPDX-License-Identifier: MIT

package judgefold

import (
	"fmt"
	"sort"
	"strings"

	"github.com/basdotio/AgentGuard/baselines/run"
	"github.com/basdotio/AgentGuard/internal/model"
)

// Meta is what the table's header states about the fold that produced it.
type Meta struct {
	Inputs    []string // input directory names, in selection order
	WorkList  int
	Threshold model.Severity
	Usage     *run.JudgeUsage // run.SumJudgeUsage over the selected ledger rows
}

const (
	benign, malicious, hardNegative = "benign", "malicious", "hard-negative"
)

// asked is a complete, scored answer whose judge asked at least one question. Only these are in
// any row: an incomplete answer is counted in the header instead.
func asked(a Answer) bool {
	return a.Row.Incomplete == "" && a.Verdict != nil && a.Row.Questions != nil && *a.Row.Questions > 0
}

// qualifies is a vote the FP / recall columns count: escalated (grounded and k of n), at or above
// the threshold. any drops the escalation requirement.
func qualifies(v Vote, threshold model.Severity, any bool) bool {
	return (any || v.Escalates) && model.Severity(v.Severity).Rank() >= threshold.Rank()
}

// pair is one (aguard kind, rule) row.
type pair struct{ kind, rule string }

// count is k of n for one cell, with the per-artifact pair beside it.
type count struct{ k, n, artK, artN int }

// tallyPair counts, over the asked answers of one class, the samples with at least one artifact
// of p.kind (n) and those with a qualifying vote of p.rule on such an artifact (k), and the same
// over artifacts.
func tallyPair(answers []Answer, class string, p pair, threshold model.Severity, any bool) count {
	var c count
	for _, a := range answers {
		if a.Row.Class != class || !asked(a) {
			continue
		}
		arts := 0
		for _, k := range a.Kinds {
			if string(k) == p.kind {
				arts++
			}
		}
		if arts == 0 {
			continue
		}
		c.n++
		c.artN += arts
		flagged := map[int]bool{}
		for i, v := range *a.Row.Votes {
			if v.Kind == p.kind && v.Rule == p.rule && qualifies(v, threshold, any) {
				flagged[a.VoteArtifact[i]] = true
			}
		}
		if len(flagged) > 0 {
			c.k++
			c.artK += len(flagged)
		}
	}
	return c
}

// Table renders per-kind-rule.txt.
func Table(answers []Answer, m Meta) string {
	var b strings.Builder
	header(&b, answers, m)
	thr := m.Threshold

	fmt.Fprintf(&b, "\njudge-added flags: samples with static < %s and judge >= %s, over the asked samples:\n", thr, thr)
	for _, class := range []string{benign, malicious, hardNegative} {
		k, n := 0, 0
		for _, a := range answers {
			if a.Row.Class == class && asked(a) {
				n++
				if a.Row.Judge && !a.Row.Static {
					k++
				}
			}
		}
		fmt.Fprintf(&b, "  %-14s %s\n", class, Cell(k, n))
	}

	pairs := votedPairs(answers)
	fmt.Fprintf(&b, "\nper (kind, rule):\n  %-12s %-8s %-30s %-30s %-30s %s\n", "kind", "rule", "FP", "FP/art", "FP_any", "recall")
	for _, p := range pairs {
		fp := tallyPair(answers, benign, p, thr, false)
		anyFP := tallyPair(answers, benign, p, thr, true)
		rec := tallyPair(answers, malicious, p, thr, false)
		fmt.Fprintf(&b, "  %-12s %-8s %-30s %-30s %-30s %s\n", p.kind, p.rule,
			Cell(fp.k, fp.n), Cell(fp.artK, fp.artN), Cell(anyFP.k, anyFP.n), Cell(rec.k, rec.n))
	}

	fmt.Fprintf(&b, "\nhard negatives (a census, never pooled with the benign rows):\n  %-12s %-8s %-30s %s\n", "kind", "rule", "flagged", "flagged_any")
	for _, p := range pairs {
		hn := tallyPair(answers, hardNegative, p, thr, false)
		hnAny := tallyPair(answers, hardNegative, p, thr, true)
		if hn.n > 0 {
			fmt.Fprintf(&b, "  %-12s %-8s %-30s %s\n", p.kind, p.rule, Cell(hn.k, hn.n), Cell(hnAny.k, hnAny.n))
		}
	}

	fmt.Fprintf(&b, "\nΔrecall per kind: malicious samples asked(kind) with static < %s and an escalated LLM finding >= %s\n"+
		"(rule not %s) on an artifact of the kind:\n", thr, thr, advisoryRule)
	for _, kind := range kindsOf(pairs) {
		k, n := deltaRecall(answers, kind, thr)
		fmt.Fprintf(&b, "  %-12s %s\n", kind, Cell(k, n))
	}

	perSource(&b, answers, thr)
	return b.String()
}

func header(b *strings.Builder, answers []Answer, m Meta) {
	complete := 0
	for _, a := range answers {
		if a.Row.Incomplete == "" {
			complete++
		}
	}
	fmt.Fprintf(b, "# per-kind-rule.txt: generated by baselines/cmd/judgefold from raw/; do not edit by hand\n")
	fmt.Fprintf(b, "# inputs, in selection order (the first complete answer of a sample wins): %s\n", strings.Join(m.Inputs, ", "))
	fmt.Fprintf(b, "# work list %d · complete %d · %d incomplete (in no row below; listed in incomplete.jsonl)\n",
		m.WorkList, complete, len(answers)-complete)
	if u := m.Usage; u != nil {
		fmt.Fprintf(b, "# judge usage (run.SumJudgeUsage over the selected rows): calls %d · failed %d · skipped %d · triage_calls %d · basis %s\n",
			u.Calls, u.Failed, u.Skipped, u.TriageCalls, u.Basis)
	}
	thr := string(m.Threshold)
	for _, l := range []string{
		"kind is aguard's artifact kind as raw/ reports it, NOT the corpus's surface: corpus surface `mcp`",
		"(tool catalogues) is aguard kind `connector`, corpus surface `connector` (.mcp.json) is aguard kind `mcp`.",
		"severity is each finding's own as the binary reported it (the first agreeing sample's).",
		"asked(kind): a complete sample with >= 1 artifact of the kind and questions > 0. raw/ records questions",
		"per sample, not per artifact, so every rule of a kind shares that denominator; a (kind, rule) row",
		"exists only when the run holds at least one vote for it.",
		"FP      benign samples asked(kind) with >= 1 escalated (grounded, k of n) LLM finding >= " + thr + " of the rule",
		"        on an artifact of the kind",
		"FP/art  the same over the benign artifacts of the kind in those samples",
		"FP_any  FP without requiring escalation: any vote >= " + thr + " (descriptive only)",
		"recall  the FP numerator over malicious samples asked(kind)",
		"cells: k/n, then the rate and its Wilson 95% interval in percent, only when the half-width is",
		"<= 15 points (the corpus's rule); otherwise the count and the half-width alone.",
		"benign is the corpus's assumed label, not a reviewed one: a flag on it is not a confirmed error.",
	} {
		fmt.Fprintf(b, "# %s\n", l)
	}
}

// votedPairs lists every (kind, rule) the selected complete answers hold a vote for.
func votedPairs(answers []Answer) []pair {
	seen := map[pair]bool{}
	for _, a := range answers {
		if !asked(a) {
			continue
		}
		for _, v := range *a.Row.Votes {
			seen[pair{v.Kind, v.Rule}] = true
		}
	}
	out := make([]pair, 0, len(seen))
	for p := range seen {
		out = append(out, p)
	}
	sort.Slice(out, func(i, j int) bool {
		if out[i].kind != out[j].kind {
			return out[i].kind < out[j].kind
		}
		return out[i].rule < out[j].rule
	})
	return out
}

func kindsOf(pairs []pair) []string {
	var out []string
	for i, p := range pairs {
		if i == 0 || pairs[i-1].kind != p.kind {
			out = append(out, p.kind)
		}
	}
	return out
}

func deltaRecall(answers []Answer, kind string, thr model.Severity) (k, n int) {
	for _, a := range answers {
		if a.Row.Class != malicious || !asked(a) || !hasKind(a, kind) {
			continue
		}
		n++
		if a.Row.Static {
			continue
		}
		for _, v := range *a.Row.Votes {
			if v.Kind == kind && v.Rule != advisoryRule && qualifies(v, thr, false) {
				k++
				break
			}
		}
	}
	return k, n
}

func hasKind(a Answer, kind string) bool {
	for _, k := range a.Kinds {
		if string(k) == kind {
			return true
		}
	}
	return false
}

// perSource prints one row per (corpus source, class): the samples the judge asked, those with an
// escalated LLM finding at or above the threshold whose rule counts toward a verdict, those with
// any vote at or above it, and those the judge added over the static column.
func perSource(b *strings.Builder, answers []Answer, thr model.Severity) {
	type key struct{ source, class string }
	type row struct{ n, flag, any, added int }
	rows := map[key]*row{}
	for _, a := range answers {
		if !asked(a) {
			continue
		}
		k := key{a.Source, a.Row.Class}
		if rows[k] == nil {
			rows[k] = &row{}
		}
		r := rows[k]
		r.n++
		flag, anyVote := false, false
		for _, v := range *a.Row.Votes {
			flag = flag || (v.Rule != advisoryRule && qualifies(v, thr, false))
			anyVote = anyVote || qualifies(v, thr, true)
		}
		if flag {
			r.flag++
		}
		if anyVote {
			r.any++
		}
		if a.Row.Judge && !a.Row.Static {
			r.added++
		}
	}
	keys := make([]key, 0, len(rows))
	for k := range rows {
		keys = append(keys, k)
	}
	sort.Slice(keys, func(i, j int) bool {
		if keys[i].source != keys[j].source {
			return keys[i].source < keys[j].source
		}
		return keys[i].class < keys[j].class
	})
	fmt.Fprintf(b, "\nper corpus source (asked samples; LLM flag: an escalated LLM finding >= %s, rule not %s;\n"+
		"LLM any: any vote >= %s; added: judge >= %s where static < %s):\n  %-36s %-14s %-30s %-30s %s\n",
		thr, advisoryRule, thr, thr, thr, "source", "class", "LLM flag", "LLM any", "added")
	for _, k := range keys {
		r := rows[k]
		fmt.Fprintf(b, "  %-36s %-14s %-30s %-30s %s\n", k.source, k.class, Cell(r.flag, r.n), Cell(r.any, r.n), Cell(r.added, r.n))
	}
}
